### get all tasks
GET http://localhost:3001/api/tasks

### Create a new task
POST http://localhost:3001/api/tasks
Content-Type: application/json

{
  "content": "Your content here",
  "importance": "Your importance value here"
}